### ISSUE TITLE
Poll votes not working

### ISSUE THREAD

**Issue by englishwebtls** [dvdcastro/moodle-mod_livepoll#10]
Hello
I followed your instructions but clicking the voting buttons does not register the vote

What could be the problem?
Thanks

**Comment by Costarisa** [comment]
I have the same issue.  The Firebase does register activity but does not store anything. API and ID are correct. Pressing the buttons and nothing happens.

**Comment by dvdcastro** [comment]
Can you [enable Developer debug mode](https://docs.moodle.org/310/en/Debugging#Enabling_debugging) and open the browser inspector? There should be debug messages being shown which may help us see what the bug may be.

**Comment by englishwebtls** [comment]
Hello David
This is what I get:
firebase-database.js:1 [2021-03-02T11:58:21.158Z]  @firebase/database:
FIREBASE WARNING: Firebase error. Please ensure that you spelled the name
of your Firebase correctly (https://meta-aura-280015.firebaseio.com)
q @ firebase-database.js:1
DevTools failed to load SourceMap: Could not load content for
https://www.gstatic.com/firebasejs/5.2.0/firebase-database.js.map: Load
canceled due to load timeout

I hope this helps
Regards
N Williams

**Comment by englishwebtls** [comment]
Do you need my firebase login details?

**Comment by ssp819** [comment]
I'm facing the same issue with Moodle 3.10.1. Installed correctly as per the instructions and Firebase setup. Connects, and the Firebase console see some anonymous authentication activity, but the poll does not register any votes.

**Comment by dvdcastro** [comment]
Hello,

I think I found what the problem is:

When I configured Live Poll to work before, the default url for the realtime database was:

```
databaseURL: "https://" + self.projectID + ".firebaseio.com",
```

Now, it seems to default to:

```
databaseURL: "https://" + self.projectID + "-default-rtdb.firebaseio.com",
```

This is the line of code that auto-calculates that:
https://github.com/dvdcastro/moodle-mod_livepoll/blob/master/amd/src/livepoll-lazy.js#L249

We have to change it, but it would be better if we change the settings to so admins can enter the complete database url.

I'll keep you posted on the fix, in the meantime, feel free to modify the source file and re-build the JS library. If you don't know how to do that, you can also modify [this line](https://github.com/dvdcastro/moodle-mod_livepoll/blob/master/amd/build/livepoll-lazy.min.js) in the `amd/build/livepoll-lazy.min.js` file so it suits your needs in the minified JS (The minified JS is what Moodle uses). It should match your firebase _databaseURL_.

Change it from:
```
databaseURL:"https://"+d.projectID+".firebaseio.com"
```

To:

```
databaseURL:"The value for databaseURL found in the web app config on your firebase console"
```

More docs on fb defaults:
https://firebase.google.com/docs/projects/learn-more#project-id

**Comment by ssp819** [comment]
Thank you! I got it to work by correcting the ".firebaseio.com" to "-default-rtdb.firebaseio.com" in livepoll-lazy.min.js and purging the JS cache in Moodle.

**Comment by dvdcastro** [comment]
Hey guys, we fixed this in this commit:
https://github.com/open-lms-open-source/moodle-mod_livepoll/commit/0f6004bb3d32c5d811bbd46c4edbe046be3d7eee

This is the new repo for this plugin.
